import { test as setup, expect } from '@playwright/test';
import path from 'path';
import { mkdir } from 'fs/promises';

/**
 * Authentication Setup
 * Generated by Bugzy - https://github.com/bugzy-ai/bugzy
 *
 * This file runs before all tests to authenticate and save the state
 * Other tests can reuse this authenticated state for faster execution
 *
 * Benefits:
 * - Login once, reuse for all tests
 * - Faster test execution
 * - More stable tests (no repeated login operations)
 */

const authFile = path.join(__dirname, '../.auth/user.json');

setup('authenticate', async ({ page }) => {
  // Skip if no authentication is needed
  // Remove this if you need authentication
  if (!process.env.TEST_USER_EMAIL || !process.env.TEST_USER_PASSWORD) {
    console.log('Skipping authentication setup - no credentials provided');
    return;
  }

  // Navigate to login page
  // Adjust the URL based on your application
  await page.goto('/login');

  // Perform authentication steps
  // Using role-based selectors for stability

  // Fill in email
  await page.getByLabel('Email').fill(process.env.TEST_USER_EMAIL);

  // Fill in password
  await page.getByLabel('Password').fill(process.env.TEST_USER_PASSWORD);

  // Click the sign in button
  // Adjust the button text based on your app
  await page.getByRole('button', { name: /sign in|login/i }).click();

  // Wait for redirect after successful login
  // Adjust the URL pattern based on where users land after login
  await page.waitForURL(/.*\/(dashboard|home)/);

  // Verify authentication was successful
  // Check for a user-specific element (e.g., user menu, profile icon)
  // Adjust based on your application
  // await expect(page.getByRole('button', { name: /profile|account/i })).toBeVisible();

  // Create .auth directory if it doesn't exist
  await mkdir(path.dirname(authFile), { recursive: true });

  // Save authentication state to file
  await page.context().storageState({ path: authFile });

  console.log('✓ Authentication state saved successfully');
});

/**
 * Example: Multiple User Roles
 *
 * If you need to test with different user roles (admin, user, etc.),
 * create separate setup files:
 *
 * - auth.setup.admin.ts
 * - auth.setup.user.ts
 * - auth.setup.guest.ts
 *
 * Then configure them in playwright.config.ts:
 *
 * projects: [
 *   { name: 'setup-admin', testMatch: /.*\.setup\.admin\.ts/ },
 *   { name: 'setup-user', testMatch: /.*\.setup\.user\.ts/ },
 *   {
 *     name: 'admin-tests',
 *     use: { storageState: 'playwright/.auth/admin.json' },
 *     dependencies: ['setup-admin'],
 *   },
 *   {
 *     name: 'user-tests',
 *     use: { storageState: 'playwright/.auth/user.json' },
 *     dependencies: ['setup-user'],
 *   },
 * ]
 */
