import { test as base } from '@playwright/test';

/**
 * Custom Fixtures for Page Objects
 * Generated by Bugzy - https://github.com/bugzy-ai/bugzy
 *
 * Fixtures provide a way to set up and tear down test dependencies
 * This example shows how to create fixtures for page objects
 *
 * Usage in tests:
 * test('my test', async ({ homePage }) => {
 *   await homePage.navigate();
 *   // ...
 * });
 */

// Define fixture types
type PageFixtures = {
  // Add your page object fixtures here
  // Example:
  // homePage: HomePage;
  // loginPage: LoginPage;
};

/**
 * Extend the base test with custom fixtures
 *
 * Example implementation:
 *
 * import { HomePage } from '@pages/HomePage';
 * import { LoginPage } from '@pages/LoginPage';
 *
 * export const test = base.extend<PageFixtures>({
 *   homePage: async ({ page }, use) => {
 *     const homePage = new HomePage(page);
 *     await use(homePage);
 *   },
 *
 *   loginPage: async ({ page }, use) => {
 *     const loginPage = new LoginPage(page);
 *     await use(loginPage);
 *   },
 * });
 */

export const test = base.extend<PageFixtures>({
  // Add your fixtures here
});

export { expect } from '@playwright/test';
