import { defineConfig, devices } from '@playwright/test';
import * as dotenv from 'dotenv';
import * as path from 'path';

// Load non-secret environment variables from .env.testdata
dotenv.config({ path: path.resolve(__dirname, '.env.testdata') });

// Load secret environment variables from .env (for local development)
dotenv.config({ path: path.resolve(__dirname, '.env') });

/**
 * Playwright Configuration
 * Generated by Bugzy - https://github.com/bugzy-ai/bugzy
 *
 * This configuration follows Playwright best practices:
 * - Parallel execution for speed
 * - Retries in CI for stability
 * - Trace capture for debugging
 * - Optimized artifact collection
 */

export default defineConfig({
  // Test directory
  testDir: './tests/specs',

  // Fully parallel test execution
  fullyParallel: true,

  // Fail the build on CI if you accidentally left test.only in the source code
  forbidOnly: !!process.env.CI,

  // Retry on CI only (2 retries), no retries locally
  retries: process.env.CI ? 2 : 0,

  // Opt out of parallel tests on CI for stability (can be adjusted)
  workers: process.env.CI ? 2 : undefined,

  // Reporters
  reporter: [
    ['./reporters/bugzy-reporter.ts']
  ],

  // Global timeout
  timeout: 30000,

  // Expect timeout
  expect: {
    timeout: 5000
  },

  // Shared settings for all projects
  use: {
    // Base URL from environment variable
    baseURL: process.env.TEST_BASE_URL || 'http://localhost:3000',

    // Collect trace on failure
    trace: 'retain-on-failure',

    // Screenshot only on failure
    screenshot: 'only-on-failure',

    // Video for all tests (always record)
    video: 'on',

    // Maximum time for actions (click, fill, etc.)
    actionTimeout: 10000,
  },

  // Configure projects for different browsers
  projects: [
    // Setup project - runs once before other tests
    {
      name: 'setup',
      testDir: './tests/setup',
      testMatch: /.*\.setup\.ts/,
    },

    // Chromium
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        // Use authenticated state if available
        storageState: 'tests/.auth/user.json',
      },
      dependencies: ['setup'],
    },
  ],

  // Run your local dev server before starting the tests
  // Uncomment and configure if needed:
  // webServer: {
  //   command: 'npm run dev',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});
